server:
  port: 8000


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://localhost:8761/service-discovery   # put eureka server

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: service-member-get
          uri: lb://SERVICE-MEMBER
          predicates:
            - Path=/service-member/**
            - Method=GET
          filters:
            - RewritePath=/service-member/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: service-member-post
          uri: lb://SERVICE-MEMBER
          predicates:
            - Path=/service-member/**
            - Method=POST
          filters:
            - RewritePath=/service-member/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: service-others-get
          uri: lb://SERVICE-OTHERS
          predicates:
            - Path=/service-others/**
            - Method=GET
          filters:
            - RewritePath=/service-others/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: service-others-post
          uri: lb://SERVICE-OTHERS
          predicates:
            - Path=/service-others/**
            - Method=POST
          filters:
            - RewritePath=/service-others/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

token:
  secret: CdkKVDgED/8zH71UEu1kRNaeI9/rWJiGxiT+ht0u5QaVjOXKkx//t+hLqtTgwqEGWDuQaz07ze60vVX8LTnlKQ==